# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnHgeu4PDm5VC72oi3q8PIfpzTwm7uZt
"""

# prompt: generate a data frame

import pandas as pd

# Create a dictionary of data
data = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Print the DataFrame
df